[package]
name = "noah/rogue-lineage-tycoon"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.5"
Component = "sleitnick/component@2.4.6"
Trove = "sleitnick/trove@1.0.0"
Loader = "sleitnick/loader@2.0.0"
Signal = "sleitnick/signal@1.5.0"
Spring = "brittonfischer/spring@0.1.0"
Timer = "sleitnick/timer@1.1.2"
React = "jsdotlua/react@17.1.0"
ReactSpring = "chriscerie/react-spring@2.0.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"